package org.crackle.impl;

import java.security.SecureRandom;
import java.util.Arrays;
import java.util.Objects;
import java.util.UUID;
import org.crackle.Address;

/**
 * Creates addresses suitable for distributed processing.  These addresses
 * by default contain a UUID and securely generated 4096 bits of identifying 
 * information (by default), 
 * making them extremely difficult to forge and globally unique. 
 * @author Chad
 */
public final class DistributedAddressFactory implements AddressFactory {

    /**
     * The default number of randomly generated bytes, 4096 bits, 512 bytes.
     */
    public static final int DEFAULT_NUM_BYTES = 512;

    private static final class DistributedAddress implements Address {
        private final UUID uuid;
        private final byte[] bytes;

        public DistributedAddress(SecureRandom secureRandom, int numBytes) {
            this.uuid = UUID.randomUUID();
            this.bytes = new byte[numBytes];
            secureRandom.nextBytes(bytes);
        }

        @Override
        public int hashCode() {
            return Objects.hash(uuid, Arrays.hashCode(bytes));
        }

        @Override
        public boolean equals(Object o) {
            final boolean equal;

            if (this == o) {
                equal = true;
            } else if (getClass().isInstance(o)) {
                final DistributedAddress other = getClass().cast(o);
                equal = uuid.equals(other.uuid) && Arrays.equals(bytes, other.bytes);
            } else {
                equal = false;
            }

            return equal;
        }
    }

    private final SecureRandom secureRandom = new SecureRandom();
    private final int numBytes;
    
    /**
     * Create with the default ize of random identifying information (4096 bits)
     */
    public DistributedAddressFactory() {
        this(DEFAULT_NUM_BYTES);
    }
    
    /**
     * Create with the specific number of random identifying information.
     * @param numBytes 
     */
    public DistributedAddressFactory(final int numBytes) {
        if(numBytes < 1) {
            throw new IllegalArgumentException();
        }
        this.numBytes = numBytes;
        
    }
    
    @Override
    public Address createAddress() {
        return new DistributedAddress(secureRandom, numBytes);
    }
}
